### PR TITLE
add minimal loading view to check

### PR DESCRIPTION
**Pull request by schuyler1d**
This is more a stub that you can edit for us to include on the petitions site.  What should render that achieves the goals of:
* force-loading fonts early (i.e. we need to have an instance of each font)
* force early-loading logo.svg (needs to include the logo)
* is as absolutely small as possible

I'd like to suggest we merge this, but then someone comp something/edit this file to use minimal inline css to render it.

### CODE REVIEW

**Comment by schuyler1d** [comment]
screenshot of what it looks like currently
loadingmoveon

**Comment by hi0ctane** [comment]
So @schuyler1d Ive placed the logo over a black bar so that it looks like the header.

screen shot 2018-04-13 at 1 01 07 pm

**code:**
```
 <div id="root" style="background-color: #000000; text-align: center;">                                                                                                                                       
       <img src="images/logo.svg" style="position: relative; top: 43px;" alt="MoveOn Logo" />                                                                                                         
         <div style="position: relative; top: 60px;">                                                                                                                                                      
            <span style="font-family:'Roboto Condensed Bold'">Loading</span>                                                                                                                                  
            <span style="font-family:'Roboto Bold">.</span>                                                                                                                                                  
            <span style="font-family:'Roboto Regular'">.</span>                                                                                                                                              
            <span style="font-family:'Roboto Medium">.</span>                                                                                                                                                
       </div>                                                                                                                                                                                             
 </div>
```
_suggestion:_
I think we should change the loading message to something more human sounding, less machine i.e. "We'll be with you shortly!..."

**Comment by jparkrr** [comment]
Maybe we can add a message about making sure javascript is enabled, as this is what they'll see if it's not.

**Comment by schuyler1d** [comment]
How about

> Thousands of activist bytes are marching forward to build your page!  Just a sec.....

**Comment by jparkrr** [comment]
Also I think the black bar with logo is a great idea! It would be cool if we could inline some media queries to make it match the mobile one as well

**Comment by schuyler1d** [comment]
Language signoff on 
> Thousands of activist bits and bytes are marching forward to build your page! Just a sec..... [loading....]

**Pull request closed without merging**
